server:
  port: 8080


spring:
  thymeleaf:
    mode: HTML

  jackson:
    time-zone: Asia/Taipei

  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/cart_demo?useUnicode=true&characterEncoding=utf-8
    username: admin
    password: 15903711ff

wfg:
  method: 1 # 1为雪花漂移算法，2为传统算法
  worker-id: 2 # 机器码id
#  doc:
#   swagger-ui:
#     enabled: true
#   api-docs:
#     enabled: true

#  jpa:
#    hibernate:
#      ddl-auto: update
#    show-sql: true
jwt:
  header: Authorization
  iss: test123.demo
  aud: tes123t.demo
  secret: ${JWT_SECRET}

  openapi:
    server:
      url: http://localhost:${server.port}
      description: Local server


